apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:CUjhuyjQkRYnHNzoF/cwvzWV9WUM1zQBYMJZDBU0YM/dzShr,iv:FOTZjEf2Q7vGkukwBCULFYYZcKKYzqeVZKm99qa/ZWw=,tag:IKRxjj1Du+zOTuDAwN1yMQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:3ekmSBERqP9TLdIyMqms1vB44U3AJN1JjE8/vXP0CwZ4g1df9w9eNIMp3mACRYLRN1QkDywfRaYtElwKu+NimqvMWGxneBs6KFmsA+1y15lWtKGWuQmm1nGgvcJZ5sCU7IifG6gXJeuCvx3dtE4QWu2V2l1WoJLdiuvTBlQ13maQ+EeJfUjS4w3UDY2Sc90QBuqGlrOz74qnQ1XQyAmvgbNltbtXfLSYcezhEynrbw==,iv:XMh3pD+XKMfiIL7abVEBjiQxjNyqU6Ti42jnx883/+Q=,tag:FPwWwhbDMrOFeD/xlWWQJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZkJhZlBBRHlYSURRN3Bm
            d3YzKzRweWtpNjFTTWJJdXIxOVhndmdVMWt3CnU0Q3pQWU9RcEJLdlIwaHRyc3la
            SjhaK2RxWFlQRmJJZkY3WnNWSlVWZDQKLS0tIEc5M1JVNWV2d29yaGxNZ0d3bnE2
            Yjd5M3Vycyt0MUlWbEhGS1g4bzRiWWMKeq2CcxpsCgpEutkIRGvFNFxfXKDSpsq1
            ALXasuUCRkGHwoOxVBg3tXn1Xe0mhylJn8H/hXkWdwXD2zlG7kfkpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T23:30:43Z"
    mac: ENC[AES256_GCM,data:KA0/Fewpt/+LQlkZffhoAoXjL1WguY8v6KM+sXnALKYRPuQtMe4pobxgmuPGf8oslZgHLbWgfooydNh77QSgLqff4Z/h4o8iBIzIuE5KcEuimBH5dKendzcuMA8UhkXqoxvN0Hr4pwu1cVcLk5A7IKrboFwjoag64jvJySCFu4s=,iv:6m8Aj1PJPpoup82Kqv/NnT0gkdvKO/B/Js6JxS0GfvU=,tag:5OcOkdED2HJjNQGi+gxgdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
