apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:eSfmq6Ov9VP3s5KYhkPKMgEbAGm2hnq5Ha+el+Rh4FtJQbHL,iv:m2gM4vf9CIqpqnIXbX/TEN8PjtLjVmkr1DbSxUPOK9M=,tag:1jk/g0tb2znmlWP4MkB2Vw==,type:str]
    credentials.json: ENC[AES256_GCM,data:3cpgGa364MHuA67X1Dmf6CVIsnpF15WB7VAqjyRC7GTELrpU7twOO8fAG3FtO5krFjBwK/P/UIPOKdZlJWewuKTscElLGyB+9M6UHLw5IUx4w6e+hr2BTNXA5lf/M5PoQxDgXR8R3vj69m96LZKHj//DoMJT0WyPuZpIZGn2AYRfBHHcWMbpDOuT87wzyj5zLEwfSXhA4fvyap3/p8/3Pq2sUqJvnQlacrp2nVz1fw==,iv:rhW5XfSdZbk2nmxJ3ZfvWyrrsp8aM4hSBO9IfJfouWQ=,tag:lIwoUP95YUTnCgwXQK0i7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYXJRclVQaE9wUDgya1pO
            T2IrZWRnTVNpa0pkaGY0WDREaXhvdXhrT2o4CmZxRTE0ZHJSQ3BhM3YzNUc3VU5H
            K21YbThzT0N4N0FWbEdLTkcwNVdtYm8KLS0tIEx6aC9laWRnVHFqTTNEZVlIUUxm
            VkFWaVU3QVJlQndETHBMd0hhckNRRDAK7Tsz8FqHO0muoZYxvA3+nt1vxgwoC8kd
            yioQgSzQbc6zM/HCRVr537dOzilVwaaTNfVn9yKEnH2h9fWyfJpGyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T22:12:57Z"
    mac: ENC[AES256_GCM,data:Vpgmks2VZXV0Q4/OazSY+WecdODg+paFpQXKllbigLgbDl5z5AgOhEHfztlJbFmQEKDjVvIhVIVGXfOiUwzOwmxQqL2ep4W7kOkBJZENzgw9gwnAKyk+GEP9bxwfvx2U6ENgNXFA9aBwLhwwmfKLkQcxfdXL/31jtOhDpJG+qj8=,iv:tn/0IRhxmcTC8hacG9qaAmr9PoC3JKnIf9SMoo76yq4=,tag:yD4rzM5lZ2ABOH4IEiwxvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
