apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wMSyZTEwLLuF3Gww/2DNtBCAW/xy50BiFNdTZ4OHUkWpQXut,iv:jX47fQ7WvxZI1XvCl7qxtrSp71Baxq5hyoVP106owEk=,tag:sD6LZwHwbX34n5WmRneVgg==,type:str]
    credentials.json: ENC[AES256_GCM,data:LlriJMtK1Er+BQmC5hWbPoLi95Jwl8IBT6iojP/4EATrvyuUG4NoWyFgk+QXa4BqvTeM3fPL3gh3F7bggClnotlvsOVeISFDwnMgfWFSz62EN7SCnWxQ/kbngKQk1GhFE01GoKu0RvguICWdaLziQ74pjPixHstOj/v+O/5pcGCc3j0mNKVCRerPb/Ivs+CAxErKRjTSVCYBUC9o3ZHSzcNTd0iK3N4aM3lx+WwJTA==,iv:vP+YFEAORhOqRuAaB1gW6OquT4n2NENE2Cq9IfGfeGA=,tag:ylQ/jF26fj70WQ+pi+/81Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSWRncnhzNDlDNXRMM2lP
            WENBSEZ1d0hTZGpkYlJnMERlUUY2aU05Sms0CllodHk3SEdIdG8vdytEK1VqaUlU
            NDg0Z2huS1R5SHB5aURSL2JkckxMc0EKLS0tIC8zSW9XTkNKRHpna1hBYVZWbTJm
            R00yRThRaUFPR09KK0NyeVNIU1Y1YmsKrdZtvZ5yBzIe/b10OGvDxoJjmL0ADH0z
            bV2j1LifEVkpsZZylmygUH5nLWjvjTWPkwBYjT8qZZUbekCJLsebLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T22:33:58Z"
    mac: ENC[AES256_GCM,data:LBqIyK24EVz8ETohf+aZ6GrkhIFiq9gQovw+8ZqkHRFgTVv/MP7j4rDp7PP+XlxJdevsWYHlI79JMGNcoKBzgZEKixVvduQyyvEvmvb4o62IZFxVDI9haAPaJ3r0PFIgP0NmIXpH1Gv+qnfJVlrxtrQ9UZNHioLkZlcTsoApfvE=,iv:Y0Cu5HAAIsu/iAx/qEmTxRKTM6EbBT1dWow3Tq8Vvjs=,tag:b/Sm/u4J4IGuox+zR9K8MQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
