apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:HYmSax8h9zOu2Km7p3piZlznBocsp3+lzeIdnWDec5YzoE9dKrRjSg==,iv:aXf6newMYuwLeNTXoi6fF6mhJk+5YYlzJeIHK40ZMVM=,tag:Y1s6WIxHaDR2WpaX/XLTfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS0xXNVhRTjZQSXoraTJF
            UXJwL3psL1JKaWN0Z2JYMXVDcUlDMHU0c0ZFCloyMGlGOHVpZ202QU1hZnltVFNV
            UDlYak1kZXhmRjhYZWNNTUdWQ2FYNFUKLS0tIEZLVE5Mb2RmSzlZZGpubVNhNWVD
            RE8wR2VtV0dkeVdMVndxeC8vSkNSTHMKMSPU+XWWo8M5ZDcTiW3Lqye2BGN4mApm
            44ASdPDzKzTo7rerYGHl4jYt8pJSziuUUtsPETNRiKnuFiiJIZdvXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:00:06Z"
    mac: ENC[AES256_GCM,data:JEG8wVh/uEv5fQW57wVgR0fPM+rMUY8Y29wK/nYoyi5g+sW+jXSYte0lNqF48CENQPj9mPNewZmk139ueQ1qRBfEZTAZe52uVDmqkFfwaGGVw9vlwmObjE2eqmXTzPSgewiw85kK6m+4dWjnAjAtYxxmuGof1x3vO0LkL2jZok4=,iv:IlDjaCLeOQaNzZxQYDUqhxYoVzJdrUjbPcMhRdDFvFA=,tag:rQ02kjdMWKaOb0KONIfDow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
