apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qrTurNVfiXMZ+n30HI0Zqv2XkqxAaNR8NvKp28U0xvDy8Q/yOw8Tpw==,iv:NQRMdjke4BsCZsHoYtsKt73i1Z+LKetP24yuVLoXgC8=,tag:g50C4eBZhKR+BaU7WiJ+nA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZk1IbWRYRVcvalZXQTQ5
            UFpJbWk3TGhtVENXM1NUV2l2cFp5TzhJbUVvCkYvb2M5ZjZOOUNCTDBoYTNNVHNq
            ZnRiVDJIR3YyWitVMU9DaWFKazAxbkUKLS0tIEFaWHFFNGFZSUlVWGtuVGxhZWJB
            RnlzVWs5eGQ0S2dYMWp4VFJPbVFQM0EKZdQRHgUdDy/Q2vBzWHcnt0AKDxHm8YXk
            oq3vWY/0VR7fSjXe8SanO2TuqGY9FfS4EZ/RiwS3JgBp1AjLxt5DUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T01:01:01Z"
    mac: ENC[AES256_GCM,data:0ZHio4dZulJavc55syMRN1oz/abcD4+QpyCQqvMSLkn9Meo6dDcRYvddQvcuhccmczJ63YRm2IMhCrstoMdn+BAi6W2FhIb+UWQB1mvgr7eG4DtcncroyUAXGpd7v+znmoUBOookw2+ueQZ2+Y4UO4EgVQ9sLni27mAh1Eh2uWI=,iv:LzkSA8D9t+7Sx419Pv+2KPRMvmH99hYYPMhdoI6fCUs=,tag:BDYAnZBEUyhK+G5yB13yRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
