apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:DOrbcLfwp9vdMSV9AqBUryxGV1U0rjFDL8DSkIjULC/ANUcbXJB2yQ==,iv:WpXYa9XFW5phJ0DzSyGbtRTyIBB8hmfR4FiOonQDIY0=,tag:CX81f1xNe6tcjXdv7vaA0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcmpoZ2hnYXNpYmIyeDNL
            T0E2Ulp3V2ZYaE5XcmNDSVZUa3N6NCtuWHdnClFwMTBEelM5RmgvSkpNS0w0UlBW
            Ri90d0N6dW5UOUhLVlZxK09UUm1QOFUKLS0tIHhhQ1JRSU1GTGhIZUpKbWM1aUlp
            L2NuYkxHbmVGWVJqWi9CdGhPeEFqK2sK3PPgW7TAvxR9Wo0/4mTQfdkPOtVaUuQO
            y8y2v9Xsd/vfKXk7Cg6EnG1Y1IMEdEu0KmzqlWNOl1N04AxepQtr2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:46:42Z"
    mac: ENC[AES256_GCM,data:6g1ZwixtDoMz+VMez8GiIEEvSKz4bK/fWKJb76Tag6cB4xT0B0d91QMjS39OLQlkxCWL7b9X53ry6Mg74OL4FHdrM5KXY9GMO6GFgCzZCcORWHTaMMgj7BlqpzAMF+lW4oLMXrPy7jqrnaBhNUbnc+iR4ZASjfnid/TUp+43Egw=,iv:qhlcf2vzR5TzTpuRBChTQjUxg+jOdmr+05EgAYjjI40=,tag:he8MApJCkN2O9wOWR9mQYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
