apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:KErRoYl01D2+,iv:Dk6m3sK5rRlORxkq/LyuwoFOlYfPF0HZRhlmJn3Ut6E=,tag:f9aQhVsM2C+MpI75noGb1A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pbSHbK60ojcJoAk2vD0JxjStQLIVbxk=,iv:IRfY5GcNGG2ElQryJFmsDaAI9VluPDUBPWaLdWcNxm0=,tag:3Q2wBw1oeh3OpDpa23kL1Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:C+TBNV+Jk1ljxEQUWlmnDL64ltmXtJy6ThU30iwQu8zMTq1H,iv:wA4cMCu9I/Lqgx1UI+CVThpIpaRQN5wrBU7ze+l8lhU=,tag:n4OVbYhG9FUEFaalJghLaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBINVlIa1l6VzdSR1VCbnFs
            K3V6SUlJN2VaOHZUVDdCWGk0REMwNmpuZG1FCm4rQXlMTUl1dCs3SzdQKzhHWG5x
            NWRKeVJJdzMwZFVOazBlVkNjMmYvamcKLS0tIFBHek93RUNFci9HVUlXN0FTTUNS
            NXMwaFAwNm9wZXNQNGR0Tmk1RFV0MTQKZ5FbKMF3Ow3qB87eCAXkTNdyD51zswnd
            wveMb89/PcWX3uV8hgl1gopWbqQxqbIFH6lSST/okJAC5zshWFA+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T21:16:45Z"
    mac: ENC[AES256_GCM,data:M5yTe/ou8wqjlnW20Utl9xUGq7XST2Fy7lDG2m+Y6IuptYhevkFU0osALy2AkU230s5wloOr9AXiAKut9q5E/ZnyMpADxcF90rs2mykFtBtIM+5sWf7ri8vIKj1FYkLWcqawAX7vwkODAezFWh9H4NsTn4qh1gmt6jcTB10dadk=,iv:ljg1eXdeCFC5hN+aYWYtghgnuiG3koVy1skxyCcl3mU=,tag:mLrH0zM9KslgBp4lctI5PQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
