apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GSgWORyolG7N,iv:L5d37rUWB/rYw1SCAi35URILYZmzFx4Ia3JEeuiD4lo=,tag:K94n+OHOsKE4XtBxHOVfCg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:xou00/ITezvegLvte3Wc7yN42uZsRfU=,iv:xP4A86RCn0+6HOFLHRrf/pW7uoM7ymt05+g/i8YVPl0=,tag:JaiRRagkGAxYjpkzjjPf7w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PNazX4UScPzFRBrdcjYf/tg8EV+XHpHhFVwB4YXCdrRFvF/Z,iv:GQzJ+4fUTq+gLFWN2R+BhbyLewZ0X1kN1PapafziD04=,tag:m9eCLaKZ1+TloAMZccY9Qg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S1lWblBjMFhxK3pYZk1R
            YXhnVnBjZ3FqY0FlMHEyUEROUjRSb0k2S2s4CmdRSTFHR0N6TWV6bUFOSlQzQUNj
            MkZqQjB6MXdwekV3UUFITjlpUzZyZHMKLS0tIHYzcm10YzhROERUMVlIOVBzTURF
            OC9EK0VQMzJJMUpwODBJM1lMV0hLRnMKlG3mGTVDeQW4IIboZWwy0abKic812NCG
            vSNI0GApCRBhtx/9g6tZWT/KiSiBxJ5sBXqwxTVlHvF/+iLSQdmu9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T18:16:44Z"
    mac: ENC[AES256_GCM,data:5aUALeHTtSx8dK4/6HsMYHYpHal5FvwritYRfOpOoCP3g5OShyGe1D3xDSwojjegSzc6+qtatXBBJY3/xVW4e4SHwVvHIrhaJo0Z3YFUv/JrTnktgk9B8JbQz+65ID4u0yzZdkscTrfjYjrUmn0z7yPEkdY1VpyjDxqp3/XstLc=,iv:RODpsm+r8F92xYDQ5cONCj0pIEpmARjriV9SwX13qqQ=,tag:NGnH5DRIgWmCC01YVAiD5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
