apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:rDLzxg4HaKpN,iv:PJ6ucg4GaErhcI3p8/fKQJn/6P6Av/tL+zKe70hI7cs=,tag:nBszcrMcLmOqoUVjT6NkXg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:2Qxx7qkzD49avSVKp2bt0glTpxEFFjc=,iv:1s8h6IjeYrzgQ6/khdsFee1H/+OhTT5xJai72xWKqRg=,tag:yV1D4RdqzcGfk+Qu5ht/kQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ng7IvCEflKNcrDgu172fPByHsmICQLsM/6ItaOgrlqmzYD21,iv:pv64327aeKTvJff2rLCTK+9CwyQjIuHDaSFGgxKB7hQ=,tag:UVlCv77LDN1WKx9SXMTTsg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVlVyV2QyaWVpQ3grRzBz
            N3BNOGVGR1dWeHB5cHNBaUZxb1AweEIyOWlzCnpVVExDMkhSdzQzcmRWWHNpOVlm
            QXRrMUdDS2pLbHpSeDExMDQzalAwSG8KLS0tIGFlNWFZaE5BY2FqbjcwUTFOaVRC
            Vno2M3V6V1FKcDA4Ui9HdjlXdkkyYTgKZCuJYnT74N7MCAMlWBedxboFDapdrYJu
            vFwpoklOQDdeyUoOfTpVfeDMdyib4vwZQmbpUL3F107IITkiiFJL4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:05:28Z"
    mac: ENC[AES256_GCM,data:rXlGXgkEJjlUQ8r2Ph+MVCUU8f+/5sZi643TLbFDatR7NaHH0ukApziq6GQAbuWxqDVh6OJrQhZYmQY5ZZUYmRrRduVy+k8TJgOcOuTNQB3pf49jTwjZ/WucyKPFnNu+Hj4ZX1ExDEBunEjBIoeCnYZu5FCCYHXLVhe5zaSRQfc=,iv:xwsKqtpr5PfSLOB+6D+kS3S1OyMupMJISjAjR94O5lM=,tag:D5xCReJ1+z+M0B/97tjf2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
