apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:QVDvqWnRY3k6,iv:6ONGMQMIhAe61pntI/WFlcc2Zks1LogTuey+2SD3ZEo=,tag:+4jgLN4oE/Grh3Ygfm1Lwg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jmnZKxBcOBbhBObhb/wrQhtcl6RKbnI=,iv:kOBjzE76mACcyHMZ8boawRdDG5HquAx2TRsmqDHru8w=,tag:UGBneR5tdC3rwbtjPKbH3A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zB3TNEvG0SrR2VxwladbqMfBUYepUSL3dYtuLwExq2adKEjs,iv:QQ5uA5gIDZ/ufZSWkdpBTwM+o7xY2jGWGU/27S3GaNM=,tag:q9DXf1R3FrCf6KOHlH6KZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2JyWnBMbDhydjN3Znoy
            Vk9IR3pkUm0xQXN2aGVpTWhsMURjN3kxMGhJCmY3WW9GWXYxcnRhNVpHVjFwbHBS
            QndQNHgrSGJ6cUgyVXhGNGJKaVk3RzAKLS0tIElmMjRCTFF3K1NYRk9hdlRCamUx
            SGhxSk9BVTVJN0kvT0hiVm5LckplbnMKgTWHw6dAZQ1Q8e0z8/9j2SKNrQroO3jU
            C8t/ida2W8soE8P16Ux+Fs5ERQH7yhzWCzKvwGKWHsWmRGPbux31yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T23:30:43Z"
    mac: ENC[AES256_GCM,data:Mk8Yvdd8lRQ2h8luMDQCmD22ROPsxJdWcKyCnrZoTTctefPvElIuTqUrdq+b8nx7MQAVd9utOhRDjPh+fkqjfZzeZPzF+RghfjVbldCW9JUVQdmtNZaU4A4CU16819gadCebysnp/hXcriMsE17HlpcPDYgtpbh73LD87RVEnWY=,iv:Z64ySPPWNot6is5K/55IpnHxrcRr/1/9F4CTSUNA+m4=,tag:cnDPAPfRFJGujQco/E06hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
