apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:n30sygyNPS2ziDLk+9fRHJzamAXhBdao3WkdHERNDdM=,iv:/2gKyKoHyRiSqWcXZDQY21c0S+yeW7HLsFFLk06C/Tg=,tag:n+JX6eVCk7Z7H0hBwQbm6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoaGMrWnhaeUtKaTlnQkF0
            Mm1IektWS1hNR09FbFM4dmRDN1pwazNwQWhNCndxMnpTMlExWEtyQ0JKTk52Tk9p
            WC84b1BESUhOWWJrckNEeGN3TEpSbUkKLS0tIERVQVhIOWFnaGlWR2ZubHBXdzFU
            NXFNcnlDQnhLbnI4Rklrd1h5Mi9SR0kKu1EJGFFPiL1iBuXIZkGBTaDGVshC2Q9a
            JB0W6imH8+3JtuMh0HFfou0O6tDjcW2EqC6fNAoCzOapy8dzc/BqFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:05:28Z"
    mac: ENC[AES256_GCM,data:bXuZbQhKQQ2zH1oRwl2fuksfNcZuEQNYztztNvgC2GWtkCHn0R425nVuY2/sw6uaJvwHxNAd30S85z1e+Jd7gIiPnMUSN1zQaYtCF+GCimip/xlrnsu3c1NDVCQw0xh+K2GpYmoB6tNSyFhQb5+0/p8osN1TdKJ8G6IRu37UpaI=,iv:vc3VJHB942x+M3aLpglS+7Tc5T+GSI8uODBr54+MUr8=,tag:UM6WZHB9O4VpyWf8c2Sjow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
