apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XMcUGXMo5u4JzcvRoz+C6adOPc2Q5j29gc47GKhQaHg=,iv:EQZKOlmaDHHqJDpuTLabRX4UMgmdG9hBxtfNGXqzCFY=,tag:AHdfNEaMSEFkMZsV4N+bCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYlhxdTR4QW9mZWVPTXh3
            Zm9RUWpoY1MvZHJhVnVSZ0ROQzQxdHQ1SGs4ClJwN2Q0cGFqdTFZdmpQeCtqaUh6
            Zkp1cTJvamVnbUxacXNpZklOMVJLK0kKLS0tIEo0U0J2SU9aeUR1YmVydjRNVjM4
            WDRLeUJISXk3V3hreWtBWG1pVXJkSDQKsyt4cAprz0Y9wYkgGljvZH44/CoW+i3c
            9v27UWHsh/y5caX4lIEDd8Sgc9OWR3m6mgmeacT+qd32qLSpQ6HErw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:00:06Z"
    mac: ENC[AES256_GCM,data:c0VtKk2GSn1U6iua5QwAWcFvbnyyitvs6Y64nrJgfaDjq7NG3h+CdTNl5EqcNIdUKccbfbXqmDFCm+PMcUNBGiCn/MNUYnPs2h0gRc38tQx2J1Tppu9CIIaSox0GmeDsv/AcyP6DVdR3LB5Gzt5MOtq/Qwb3m3Z0Sp2JUvNBHVA=,iv:YhLOkY6O9Vmtng4zZSOSiRAD/l6WCo8+gev8kX8qGO8=,tag:L1dnCg1zbh5MGh5wF5IyTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
