apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:7uyPZzHSiDepfiOy+rItoxR60NwynmXzVM/XEKSwCyQ=,iv:Mc6qUliw0W5xIUhpiO3g1mUuco4rC7Cmdb8ds8zMTuM=,tag:YEV/bJSYXhQaVFVv0Axyxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob2l3bU14aGdjSTZjeFhp
            MnByTTFxNy9pRFpEOTFYNWpibGNnem5YZDFvClBoZjlka2h1akN6YVJFU1JnREc0
            amtPbktrazJ4M1NpZFQ1NE5sb3kyNnMKLS0tIHFzRUE3MXFkZVRZRjBaa2xxa2Y5
            UDgxSllOSXVRMHR5WGFhWHVzdGdzOWcKLGLspmCSr0AjowmWon7BiYAcSLOwj+Y2
            ozef+o4vz0jyAJljJTdc4FGzOTzGNm8rbnUnmjU2phkD/hUReYumdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T21:16:45Z"
    mac: ENC[AES256_GCM,data:e6IBGOLEV00ZQwKu/QHojElJTKNygDtnu+WlnRwbZx1G0xYbFhfASax2ty5ld6ttMuIrkNY6mTb+9jhm2og7QCGAdPpU5/i1DNr/JMEwpbgHsqduVLxtUSBn92Q/2yJTEu8Yj2roUY1m7NWk7SicFH0S3FI2GYI24Wu0TrYeues=,iv:6QRNuHNYRsYG/DbmbHx1Vue3hLSLDhkweKxTZ53Jqlk=,tag:wFT1S/qGhFJil/OG2YDp7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
