apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:MXf9Qm/zMo1dxc5wTF+m/QfF1e5F3bjD5EP6lAAau30=,iv:l2vkr9cNyiMHcL5w7c/ddcP/Inzhog9BHFg4vYpep7g=,tag:hQhR2/l08VrPDCOhMmw2uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRGhURmFEMjh0dFdDakxU
            blc2cFAyVEE0dE5Da2twWElxNFluMnRmNkFnCm9UVFZ4bDdvNFFhZWVxSFJaRVRk
            VlNxOU80TFR1b3EwWnJNUnVuSE1IalkKLS0tIERaSjhvY2wrbkUyMEFwbDVhS09W
            aVhyMXpoQUE5VmNPRzlJbG9neFp4MGsKBCKIe0GT35xTQrzg/Ex3+aHCxxPaK3wX
            PMWVl/VHCjL+wwNIXFDJTjlEupGBapY+39YyrSo6TD5XSCj95k+6eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-23T23:30:43Z"
    mac: ENC[AES256_GCM,data:5y5yu5Hg4Om+MalSIxRoirSpvAgr/DVpiiFm3MG5/BfNJrjMoAOKqNAPgoInrfjjy6twd4zv4NomG5hj1C5MSBYaQJ9pvsn1ZwCQ47+j7JQNB52nqjxssdEkMlgFsXvFklJedlYZAFKOPUUK8VPx/h1rS3tfDpjhKLXpqh8fZPc=,iv:AQaLP/7pQ5WgIYvz9MZoPHxEIncPPfgcGGC7PpuHNkY=,tag:GY9OEeFlnAo0UwTEUJBYgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
