apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:POvid7roOVrKcp7/4JpBFgBbHS9sPTDIfWRiIQr7fCXIKnC3ZzSvjw==,iv:CgKSInIX4byz8IozE6GM1F2GZypFiaS6QHEHqxcrN70=,tag:yYeji/K7HNE/GEYBpy4r+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YVc3ejQ0NG1rTGdBVXh0
            MTJNZ3dIY1BkVENxNEFWQVNEZStTdUlzV2c0CklGTzZIa29lUUFScWNnckkyb2Na
            Tk05eUxuK3o0QWZSWFBXMHgxMTY1c1UKLS0tIGVXSVV2L3J1dnhmTzNKRW8vQXhp
            Z2FFcDVSM1NRbGhRYUg5T3Y4cFYrUHMKbtaqyXubh0mYTkbKPOjANMDenbApr8QZ
            Cmh1jT/LQRCgVRQ+Js365UxMmshayutVMVwj+SGBbORnTzfzhTlDyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T22:12:57Z"
    mac: ENC[AES256_GCM,data:A7XnrrNRmASmcpvYmKC72VIAvhqgJXeSK8lZBK30El0FeaTBaQBTc0nFG8DuIPTFzkzClo7jVJEZp/3VZti37R90CtBmbzBS0jkDLW25C8Cev9T5H9sMiyZUkKMee9rCrbeQhC6rx4a2jA9s/oLQh1/Rt0PrPFWmA2ScY5/a56U=,iv:6sJxwjGCnONlrfkx2NZhaTGOXEbVH8PhfdB8KMwjppg=,tag:dpkC69XNZkaGD5vDyRRv7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
