apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UKtCkZFnuJo8fImFJa8MHko8gyg4OlVv6z/zlKw/oUrQFasj+wjFcQ==,iv:yp9Jn23H46ZGMeM9ja9D6MEW6SJ1OTz9fDiU/eMLGIk=,tag:eja/ROeGVSb5EReGB6eiaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYzloa0xFTEpHd0o4UG00
            aWpSRGFGL2llM3pKeUxmbWFhWmxTSVVsN1dBCjFWZGpQU1dsKzF1NFNoQzRLWkUw
            UWcxZmJvYmdJeE81RkhobHZwMVl1OGsKLS0tIFVRNXlrYmdCVUFVY0tOVU4velly
            YVdsS3o3VzBNMkFDTk1ZNUZkOU4vamcKPUH7dNpKORlE7h0cchY477vCskBZX/p/
            /FNOiAU7Oq8uv8esC2ShH6vN+SwSCMQMKaPax7mu+RdagSWwFrvh9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:58:24Z"
    mac: ENC[AES256_GCM,data:72IlYGrm905ZjHNhOQdJIWKVUM1hHDaRhOBV16u43mNE3e8nJYQEdH2VVHqbeMDNYcQXDMsiuLTNIoAxyg5aYf1Q6BbZP6JAXslPjgqL7i6v3ZDAJBaOHlr4ScEaw9QvP7FdGRamaRvrmOGDKuy3TZNhzuRxxQwTxuV/Pmf0c7A=,iv:wF4k2o/tZL2xStmxbcgDu2+kEKD97HYuFdnJbf50wnU=,tag:6WQDqxsolMiClAI+5Sn40w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
