apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:MF1OIZWTCSlU7MVtO+hLiLrfPs29MHljXyLaoYV6hwZbfCZy2haRSA==,iv:66J1qvOnhBTa5y4wzd2yJV5SwLomtc0l+jmXnKXNxHs=,tag:Y0pHuj1kmq8NbV2078UoUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWnROcDRpSGc1U3QxdEdx
            WUY2UEo5MjM3SG5LU1c5YlJrcEF1VGJIWTI0CkZvT2EwQ1IzNzhoUjVyQ1ptT1gr
            ZDBTSW14NHgxQVQ1N2JrM3BrT0QzRWMKLS0tIElpYXFGUXloK3JoUzVMWnZ1bUM1
            UnBaQllsaDdEVWIxdTV4TjM1REV4Z3MKNelWMich8zsvvEpLAIfcv01ApRVCMXlT
            PeGB1tekrrppBdEEPM6knX+9CWi7NH/HJU4fGCl7kv3Ptw66/dNUpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:00:06Z"
    mac: ENC[AES256_GCM,data:FyQOFKffz/k50Dbtd6jJbtpVfCl/A7mgEqAY68+Z5auaO9dHYAG5qHGqjvWMc6dA0/1d5ahMnmqrTO4H/s5/a3wnY+c0uihiC8+hXrnGDmT+EM9D5QJKT/0p5X7mYd1R8Yw990fkcSR0nui71mvE8fHjj9Rjb28JhEw2xKeXa9o=,iv:8sQTIqa+aOIkC/EMKTdCfG8fgg7DFRNS6AX7gDNy6HA=,tag:D8UP9tj8R7WZVfxMwugm1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
