apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:yLdYv80YGIxAbZn33u6TeUqNG8iLYLVnAsbiyyqo96Y12eLZveFO2g==,iv:7mcgwBFQDA7mxYaj2Z2g2XILk32mqCZ2WdtNxUrKJYM=,tag:Gkw2rOoNP5ZCP6HyqS6S0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ljw2axxzvszjqfy96uzxxyj6j0eds7tqacp73rx7aujaynjw4uesw30e8z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5a1RzVkxZNW5GZnlueEdT
            eXRqdFVDcU1mbndVNGRJekZIZ3dmamsrZ3c4CmN3NHZSVWVRZGcza1k5bzY0bXNo
            OFVib0xSV1FUdVBGeXhDeGwxUGRPaVUKLS0tIHJLeWZjUDV0OWRtNTFxSWRaRzFN
            TXVxOXluaGwwbWw4OXBNQ2dXZlhqTEEKjyuXf8OZ2Q+sifEVolKNQ/dRTRgHtUXC
            Yh+YjlcbcTqgZJEERrh6iAf/r/Ky74ZSJ00fOCBmndYztM2lTlxJmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-21T23:05:28Z"
    mac: ENC[AES256_GCM,data:BlXHUoaCS/bBxqocuk/S9ec8PGjwnr5DsFsDiNDNn6c0vb5dM1ysXif8Co3Pw89TTr9W8b+vFDSc0ekUQwpG3wzgZ0P5DWMS/f5u28fylztgYCS+DxDv4MKWJXP0Ktv1krW3GQpM/yx6agpcsNNEteDiDJcoPWfS1grwiq9eP6I=,iv:2amRdC8pAL01RgFK+F4GdchiU+5CeYwFpY7IBshAGUA=,tag:2JNnI/sR/CW3g64zaOQirA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
